/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../../app/crestron-sdk/components/virtual-scroll';
import * as i2 from '@angular/common';
export const VirtualScrollModuleNgFactory:i0.NgModuleFactory<i1.VirtualScrollModule> = i0.ɵcmf(i1.VirtualScrollModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,
          i2.NgLocalization,i2.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(512,i2.CommonModule,
          i2.CommonModule,([] as any[])),i0.ɵmpd(512,i1.VirtualScrollModule,i1.VirtualScrollModule,
          ([] as any[]))]);
    });
const styles_VirtualScrollComponent:any[] = ['[_nghost-%COMP%] {\n      overflow: hidden;\n      overflow-y: auto;\n      position: relative;\n      -webkit-overflow-scrolling: touch;\n    }\n    .scrollable-content[_ngcontent-%COMP%] {\n      top: 0;\n      left: 0;\n      width: 100%;\n      height: 100%;\n      position: absolute;\n    }\n    .total-padding[_ngcontent-%COMP%] {\n      width: 1px;\n      opacity: 0;\n    }'];
export const RenderType_VirtualScrollComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:0,
    styles:styles_VirtualScrollComponent,data:{}});
export function View_VirtualScrollComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[i0.ɵqud(402653184,1,{contentElementRef:0}),(_l()(),i0.ɵted((null as any),
      ['\n    '])),(_l()(),i0.ɵeld(0,(null as any),(null as any),0,'div',[['class',
      'total-padding']],[[4,'height',(null as any)]],(null as any),(null as any),(null as any),
      (null as any))),(_l()(),i0.ɵted((null as any),['\n    '])),(_l()(),i0.ɵeld(0,
      [[1,0],['content',1]],(null as any),3,'div',[['class','scrollable-content']],
      [[4,'transform',(null as any)]],(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted((null as any),['\n      '])),i0.ɵncd((null as any),0),(_l()(),
          i0.ɵted((null as any),['\n    '])),(_l()(),i0.ɵted((null as any),['\n  ']))],
      (null as any),(_ck,_v) => {
        var _co:i1.VirtualScrollComponent = _v.component;
        const currVal_0:any = (_co.scrollHeight + 'px');
        _ck(_v,2,0,currVal_0);
        const currVal_1:any = (('translateY(' + _co.topPadding) + 'px)');
        _ck(_v,4,0,currVal_1);
      });
}
export function View_VirtualScrollComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'virtual-scroll',
      ([] as any[]),(null as any),[[(null as any),'scroll']],(_v,en,$event) => {
        var ad:boolean = true;
        if (('scroll' === en)) {
          const pd_0:any = ((<any>i0.ɵnov(_v,1).onScroll()) !== false);
          ad = (pd_0 && ad);
        }
        return ad;
      },View_VirtualScrollComponent_0,RenderType_VirtualScrollComponent)),i0.ɵdid(770048,
      (null as any),0,i1.VirtualScrollComponent,[i0.ElementRef,i0.Renderer],(null as any),
      (null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const VirtualScrollComponentNgFactory:i0.ComponentFactory<i1.VirtualScrollComponent> = i0.ɵccf('virtual-scroll,[virtualScroll]',
    i1.VirtualScrollComponent,View_VirtualScrollComponent_Host_0,{items:'items',scrollbarWidth:'scrollbarWidth',
        scrollbarHeight:'scrollbarHeight',childWidth:'childWidth',childHeight:'childHeight'},
    {update:'update',change:'change',start:'start',end:'end'},['*']);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovQmxhY2tiaXJkQ2xvbmUvQmxhY2tiaXJkUHJvamVjdFVJL3NyYy9hcHAvY3Jlc3Ryb24tc2RrL2NvbXBvbmVudHMvdmlydHVhbC1zY3JvbGwubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRDovQmxhY2tiaXJkQ2xvbmUvQmxhY2tiaXJkUHJvamVjdFVJL3NyYy9hcHAvY3Jlc3Ryb24tc2RrL2NvbXBvbmVudHMvdmlydHVhbC1zY3JvbGwudHMiLCJuZzovLy9EOi9CbGFja2JpcmRDbG9uZS9CbGFja2JpcmRQcm9qZWN0VUkvc3JjL2FwcC9jcmVzdHJvbi1zZGsvY29tcG9uZW50cy92aXJ0dWFsLXNjcm9sbC50cy5WaXJ0dWFsU2Nyb2xsQ29tcG9uZW50Lmh0bWwiLCJuZzovLy9EOi9CbGFja2JpcmRDbG9uZS9CbGFja2JpcmRQcm9qZWN0VUkvc3JjL2FwcC9jcmVzdHJvbi1zZGsvY29tcG9uZW50cy92aXJ0dWFsLXNjcm9sbC50cy5WaXJ0dWFsU2Nyb2xsQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiXG4gICAgPGRpdiBjbGFzcz1cInRvdGFsLXBhZGRpbmdcIiBbc3R5bGUuaGVpZ2h0XT1cInNjcm9sbEhlaWdodCArICdweCdcIj48L2Rpdj5cbiAgICA8ZGl2IGNsYXNzPVwic2Nyb2xsYWJsZS1jb250ZW50XCIgI2NvbnRlbnQgW3N0eWxlLnRyYW5zZm9ybV09XCIndHJhbnNsYXRlWSgnICsgdG9wUGFkZGluZyArICdweCknXCI+XG4gICAgICA8bmctY29udGVudD48L25nLWNvbnRlbnQ+XG4gICAgPC9kaXY+XG4gICIsIjx2aXJ0dWFsLXNjcm9sbD48L3ZpcnR1YWwtc2Nyb2xsPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OytEQ0FBO01BQUEsYUFDSTtNQUFBO01BQUEsZ0JBQXNFLDJDQUN0RTtNQUFBO01BQUE7TUFBZ0csb0RBQzlGLGtCQUF5QjtpQkFBQSw0QkFDckI7OztRQUhxQjtRQUEzQixXQUEyQixTQUEzQjtRQUN5QztRQUF6QyxXQUF5QyxTQUF6Qzs7OztvQkNGSjtNQUFBO1FBQUE7UUFBQTtVQUFBO1VBQUE7UUFBQTtRQUFBO01BQUEsMkVBQUE7TUFBQTtNQUFBO0lBQUE7Ozs7OzsifQ==
