/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../../app/crestron-sdk/components/virtual-scroll';
import * as i2 from '@angular/common';
export const VirtualScrollModuleNgFactory:i0.NgModuleFactory<i1.VirtualScrollModule> = i0.ɵcmf(i1.VirtualScrollModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,
          i2.NgLocalization,i2.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(512,i2.CommonModule,
          i2.CommonModule,([] as any[])),i0.ɵmpd(512,i1.VirtualScrollModule,i1.VirtualScrollModule,
          ([] as any[]))]);
    });
const styles_VirtualScrollComponent:any[] = ['[_nghost-%COMP%] {\n      overflow: hidden;\n      overflow-y: auto;\n      position: relative;\n      -webkit-overflow-scrolling: touch;\n    }\n    .scrollable-content[_ngcontent-%COMP%] {\n      top: 0;\n      left: 0;\n      width: 100%;\n      height: 100%;\n      position: absolute;\n    }\n    .total-padding[_ngcontent-%COMP%] {\n      width: 1px;\n      opacity: 0;\n    }'];
export const RenderType_VirtualScrollComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:0,
    styles:styles_VirtualScrollComponent,data:{}});
export function View_VirtualScrollComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[i0.ɵqud(402653184,1,{contentElementRef:0}),(_l()(),i0.ɵted((null as any),
      ['\n    '])),(_l()(),i0.ɵeld(0,(null as any),(null as any),0,'div',[['class',
      'total-padding']],[[4,'height',(null as any)]],(null as any),(null as any),(null as any),
      (null as any))),(_l()(),i0.ɵted((null as any),['\n    '])),(_l()(),i0.ɵeld(0,
      [[1,0],['content',1]],(null as any),3,'div',[['class','scrollable-content']],
      [[4,'transform',(null as any)]],(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted((null as any),['\n      '])),i0.ɵncd((null as any),0),(_l()(),
          i0.ɵted((null as any),['\n    '])),(_l()(),i0.ɵted((null as any),['\n  ']))],
      (null as any),(_ck,_v) => {
        var _co:i1.VirtualScrollComponent = _v.component;
        const currVal_0:any = (_co.scrollHeight + 'px');
        _ck(_v,2,0,currVal_0);
        const currVal_1:any = (('translateY(' + _co.topPadding) + 'px)');
        _ck(_v,4,0,currVal_1);
      });
}
export function View_VirtualScrollComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'virtual-scroll',
      ([] as any[]),(null as any),[[(null as any),'scroll']],(_v,en,$event) => {
        var ad:boolean = true;
        if (('scroll' === en)) {
          const pd_0:any = ((<any>i0.ɵnov(_v,1).onScroll()) !== false);
          ad = (pd_0 && ad);
        }
        return ad;
      },View_VirtualScrollComponent_0,RenderType_VirtualScrollComponent)),i0.ɵdid(770048,
      (null as any),0,i1.VirtualScrollComponent,[i0.ElementRef,i0.Renderer],(null as any),
      (null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const VirtualScrollComponentNgFactory:i0.ComponentFactory<i1.VirtualScrollComponent> = i0.ɵccf('virtual-scroll,[virtualScroll]',
    i1.VirtualScrollComponent,View_VirtualScrollComponent_Host_0,{items:'items',scrollbarWidth:'scrollbarWidth',
        scrollbarHeight:'scrollbarHeight',childWidth:'childWidth',childHeight:'childHeight'},
    {update:'update',change:'change',start:'start',end:'end'},['*']);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvdHltdWQvQmxhY2tiaXJkL0JsYWNrYmlyZFByb2plY3RVSS1tYXN0ZXIvQmxhY2tiaXJkUHJvamVjdFVJLW1hc3Rlci9zcmMvYXBwL2NyZXN0cm9uLXNkay9jb21wb25lbnRzL3ZpcnR1YWwtc2Nyb2xsLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL3R5bXVkL0JsYWNrYmlyZC9CbGFja2JpcmRQcm9qZWN0VUktbWFzdGVyL0JsYWNrYmlyZFByb2plY3RVSS1tYXN0ZXIvc3JjL2FwcC9jcmVzdHJvbi1zZGsvY29tcG9uZW50cy92aXJ0dWFsLXNjcm9sbC50cyIsIm5nOi8vL0M6L1VzZXJzL3R5bXVkL0JsYWNrYmlyZC9CbGFja2JpcmRQcm9qZWN0VUktbWFzdGVyL0JsYWNrYmlyZFByb2plY3RVSS1tYXN0ZXIvc3JjL2FwcC9jcmVzdHJvbi1zZGsvY29tcG9uZW50cy92aXJ0dWFsLXNjcm9sbC50cy5WaXJ0dWFsU2Nyb2xsQ29tcG9uZW50Lmh0bWwiLCJuZzovLy9DOi9Vc2Vycy90eW11ZC9CbGFja2JpcmQvQmxhY2tiaXJkUHJvamVjdFVJLW1hc3Rlci9CbGFja2JpcmRQcm9qZWN0VUktbWFzdGVyL3NyYy9hcHAvY3Jlc3Ryb24tc2RrL2NvbXBvbmVudHMvdmlydHVhbC1zY3JvbGwudHMuVmlydHVhbFNjcm9sbENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIlxuICAgIDxkaXYgY2xhc3M9XCJ0b3RhbC1wYWRkaW5nXCIgW3N0eWxlLmhlaWdodF09XCJzY3JvbGxIZWlnaHQgKyAncHgnXCI+PC9kaXY+XG4gICAgPGRpdiBjbGFzcz1cInNjcm9sbGFibGUtY29udGVudFwiICNjb250ZW50IFtzdHlsZS50cmFuc2Zvcm1dPVwiJ3RyYW5zbGF0ZVkoJyArIHRvcFBhZGRpbmcgKyAncHgpJ1wiPlxuICAgICAgPG5nLWNvbnRlbnQ+PC9uZy1jb250ZW50PlxuICAgIDwvZGl2PlxuICAiLCI8dmlydHVhbC1zY3JvbGw+PC92aXJ0dWFsLXNjcm9sbD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsrRENBQTtNQUFBLGFBQ0k7TUFBQTtNQUFBLGdCQUFzRSwyQ0FDdEU7TUFBQTtNQUFBO01BQWdHLG9EQUM5RixrQkFBeUI7aUJBQUEsNEJBQ3JCOzs7UUFIcUI7UUFBM0IsV0FBMkIsU0FBM0I7UUFDeUM7UUFBekMsV0FBeUMsU0FBekM7Ozs7b0JDRko7TUFBQTtRQUFBO1FBQUE7VUFBQTtVQUFBO1FBQUE7UUFBQTtNQUFBLDJFQUFBO01BQUE7TUFBQTtJQUFBOzs7Ozs7In0=
