/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../../../app/crestron-sdk/components/list/list-item.component';
const styles_ListItemComponent:any[] = ([] as any[]);
export const RenderType_ListItemComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_ListItemComponent,data:{}});
export function View_ListItemComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[i0.ɵqud(402653184,1,{itemContainer:0}),(_l()(),i0.ɵted((null as any),
      ['\n    '])),(_l()(),i0.ɵeld(16777216,[[1,3],['itemContainer',1]],(null as any),
      0,'div',([] as any[]),(null as any),(null as any),(null as any),(null as any),
      (null as any))),(_l()(),i0.ɵted((null as any),['\n  ']))],(null as any),(null as any));
}
export function View_ListItemComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'list-item-component',
      ([] as any[]),(null as any),(null as any),(null as any),View_ListItemComponent_0,
      RenderType_ListItemComponent)),i0.ɵdid(114688,(null as any),0,i1.ListItemComponent,
      [i0.ComponentFactoryResolver],(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const ListItemComponentNgFactory:i0.ComponentFactory<i1.ListItemComponent> = i0.ɵccf('list-item-component',
    i1.ListItemComponent,View_ListItemComponent_Host_0,{item:'item',type:'type'},{},
    ([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvdHltdWQvQmxhY2tiaXJkL0JsYWNrYmlyZFByb2plY3RVSS1tYXN0ZXIvQmxhY2tiaXJkUHJvamVjdFVJLW1hc3Rlci9zcmMvYXBwL2NyZXN0cm9uLXNkay9jb21wb25lbnRzL2xpc3QvbGlzdC1pdGVtLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy90eW11ZC9CbGFja2JpcmQvQmxhY2tiaXJkUHJvamVjdFVJLW1hc3Rlci9CbGFja2JpcmRQcm9qZWN0VUktbWFzdGVyL3NyYy9hcHAvY3Jlc3Ryb24tc2RrL2NvbXBvbmVudHMvbGlzdC9saXN0LWl0ZW0uY29tcG9uZW50LnRzIiwibmc6Ly8vQzovVXNlcnMvdHltdWQvQmxhY2tiaXJkL0JsYWNrYmlyZFByb2plY3RVSS1tYXN0ZXIvQmxhY2tiaXJkUHJvamVjdFVJLW1hc3Rlci9zcmMvYXBwL2NyZXN0cm9uLXNkay9jb21wb25lbnRzL2xpc3QvbGlzdC1pdGVtLmNvbXBvbmVudC50cy5MaXN0SXRlbUNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvdHltdWQvQmxhY2tiaXJkL0JsYWNrYmlyZFByb2plY3RVSS1tYXN0ZXIvQmxhY2tiaXJkUHJvamVjdFVJLW1hc3Rlci9zcmMvYXBwL2NyZXN0cm9uLXNkay9jb21wb25lbnRzL2xpc3QvbGlzdC1pdGVtLmNvbXBvbmVudC50cy5MaXN0SXRlbUNvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIlxuICAgIDxkaXYgI2l0ZW1Db250YWluZXI+PC9kaXY+XG4gICIsIjxsaXN0LWl0ZW0tY29tcG9uZW50PjwvbGlzdC1pdGVtLWNvbXBvbmVudD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7OzsyRENBQTtNQUFBLGFBQ0k7TUFBQTtNQUFBLGdCQUEwQjs7O29CQ0Q5QjtNQUFBO2tDQUFBLFVBQUE7TUFBQTtJQUFBOzs7OzsifQ==
