/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../../../app/crestron-sdk/components/list/list-item.component';
const styles_ListItemComponent:any[] = ([] as any[]);
export const RenderType_ListItemComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_ListItemComponent,data:{}});
export function View_ListItemComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[i0.ɵqud(402653184,1,{itemContainer:0}),(_l()(),i0.ɵted((null as any),
      ['\n    '])),(_l()(),i0.ɵeld(16777216,[[1,3],['itemContainer',1]],(null as any),
      0,'div',([] as any[]),(null as any),(null as any),(null as any),(null as any),
      (null as any))),(_l()(),i0.ɵted((null as any),['\n  ']))],(null as any),(null as any));
}
export function View_ListItemComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'list-item-component',
      ([] as any[]),(null as any),(null as any),(null as any),View_ListItemComponent_0,
      RenderType_ListItemComponent)),i0.ɵdid(114688,(null as any),0,i1.ListItemComponent,
      [i0.ComponentFactoryResolver],(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const ListItemComponentNgFactory:i0.ComponentFactory<i1.ListItemComponent> = i0.ɵccf('list-item-component',
    i1.ListItemComponent,View_ListItemComponent_Host_0,{item:'item',type:'type'},{},
    ([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovQmxhY2tiaXJkQ2xvbmUvQmxhY2tiaXJkUHJvamVjdFVJL3NyYy9hcHAvY3Jlc3Ryb24tc2RrL2NvbXBvbmVudHMvbGlzdC9saXN0LWl0ZW0uY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Q6L0JsYWNrYmlyZENsb25lL0JsYWNrYmlyZFByb2plY3RVSS9zcmMvYXBwL2NyZXN0cm9uLXNkay9jb21wb25lbnRzL2xpc3QvbGlzdC1pdGVtLmNvbXBvbmVudC50cyIsIm5nOi8vL0Q6L0JsYWNrYmlyZENsb25lL0JsYWNrYmlyZFByb2plY3RVSS9zcmMvYXBwL2NyZXN0cm9uLXNkay9jb21wb25lbnRzL2xpc3QvbGlzdC1pdGVtLmNvbXBvbmVudC50cy5MaXN0SXRlbUNvbXBvbmVudC5odG1sIiwibmc6Ly8vRDovQmxhY2tiaXJkQ2xvbmUvQmxhY2tiaXJkUHJvamVjdFVJL3NyYy9hcHAvY3Jlc3Ryb24tc2RrL2NvbXBvbmVudHMvbGlzdC9saXN0LWl0ZW0uY29tcG9uZW50LnRzLkxpc3RJdGVtQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiXG4gICAgPGRpdiAjaXRlbUNvbnRhaW5lcj48L2Rpdj5cbiAgIiwiPGxpc3QtaXRlbS1jb21wb25lbnQ+PC9saXN0LWl0ZW0tY29tcG9uZW50PiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7OzJEQ0FBO01BQUEsYUFDSTtNQUFBO01BQUEsZ0JBQTBCOzs7b0JDRDlCO01BQUE7a0NBQUEsVUFBQTtNQUFBO0lBQUE7Ozs7OyJ9
