/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './snippet.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from 'ngx-clipboard/src/clipboard.directive';
import * as i3 from 'ngx-clipboard/src/clipboard.service';
import * as i4 from '../../../../../app/crestron-sdk/components/snippet/snippet.component';
const styles_SnippetComponent:any[] = [i0.styles];
export const RenderType_SnippetComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_SnippetComponent,data:{}});
export function View_SnippetComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),15,'div',[['class',
      'col-md-4']],(null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i1.ɵted((null as any),['\n  '])),(_l()(),i1.ɵeld(0,(null as any),(null as any),
          12,'div',[['class','input-group']],(null as any),(null as any),(null as any),
          (null as any),(null as any))),(_l()(),i1.ɵted((null as any),['\n    '])),
      (_l()(),i1.ɵeld(0,(null as any),(null as any),1,'pre',([] as any[]),(null as any),
          (null as any),(null as any),(null as any),(null as any))),(_l()(),i1.ɵted((null as any),
          ['',''])),(_l()(),i1.ɵted((null as any),['\n    '])),(_l()(),i1.ɵeld(0,(null as any),
          (null as any),6,'span',[['class','input-group-btn']],(null as any),(null as any),
          (null as any),(null as any),(null as any))),(_l()(),i1.ɵted((null as any),
          ['\n            '])),(_l()(),i1.ɵeld(0,(null as any),(null as any),3,'button',
          [['class','btn btn-default'],['ngxClipboard',''],['type','button']],[[2,
              'btn-success',(null as any)]],[[(null as any),'click']],(_v,en,$event) => {
            var ad:boolean = true;
            if (('click' === en)) {
              const pd_0:any = ((<any>i1.ɵnov(_v,10).onClick($event.target)) !== false);
              ad = (pd_0 && ad);
            }
            return ad;
          },(null as any),(null as any))),i1.ɵdid(212992,(null as any),0,i2.ClipboardDirective,
          [i3.ClipboardService,i1.Renderer],{targetElm:[0,'targetElm'],cbContent:[1,
              'cbContent']},(null as any)),i1.ɵpad(1),(_l()(),i1.ɵted((null as any),
          ['copy'])),(_l()(),i1.ɵted((null as any),['\n    '])),(_l()(),i1.ɵted((null as any),
          ['\n  '])),(_l()(),i1.ɵted((null as any),['\n'])),(_l()(),i1.ɵted((null as any),
          ['\n']))],(_ck,_v) => {
    var _co:i4.SnippetComponent = _v.component;
    const currVal_2:any = '';
    const currVal_3:any = _ck(_v,11,0,_co.code);
    _ck(_v,10,0,currVal_2,currVal_3);
  },(_ck,_v) => {
    var _co:i4.SnippetComponent = _v.component;
    const currVal_0:any = _co.code;
    _ck(_v,5,0,currVal_0);
    const currVal_1:any = false;
    _ck(_v,9,0,currVal_1);
  });
}
export function View_SnippetComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'snippet-component',
      ([] as any[]),(null as any),(null as any),(null as any),View_SnippetComponent_0,
      RenderType_SnippetComponent)),i1.ɵdid(114688,(null as any),0,i4.SnippetComponent,
      ([] as any[]),(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const SnippetComponentNgFactory:i1.ComponentFactory<i4.SnippetComponent> = i1.ɵccf('snippet-component',
    i4.SnippetComponent,View_SnippetComponent_Host_0,{code:'code'},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvdHltdWQvQmxhY2tiaXJkL0JsYWNrYmlyZFByb2plY3RVSS1tYXN0ZXIvQmxhY2tiaXJkUHJvamVjdFVJLW1hc3Rlci9zcmMvYXBwL2NyZXN0cm9uLXNkay9jb21wb25lbnRzL3NuaXBwZXQvc25pcHBldC5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovVXNlcnMvdHltdWQvQmxhY2tiaXJkL0JsYWNrYmlyZFByb2plY3RVSS1tYXN0ZXIvQmxhY2tiaXJkUHJvamVjdFVJLW1hc3Rlci9zcmMvYXBwL2NyZXN0cm9uLXNkay9jb21wb25lbnRzL3NuaXBwZXQvc25pcHBldC5jb21wb25lbnQudHMiLCJuZzovLy9DOi9Vc2Vycy90eW11ZC9CbGFja2JpcmQvQmxhY2tiaXJkUHJvamVjdFVJLW1hc3Rlci9CbGFja2JpcmRQcm9qZWN0VUktbWFzdGVyL3NyYy9hcHAvY3Jlc3Ryb24tc2RrL2NvbXBvbmVudHMvc25pcHBldC9zbmlwcGV0LmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvdHltdWQvQmxhY2tiaXJkL0JsYWNrYmlyZFByb2plY3RVSS1tYXN0ZXIvQmxhY2tiaXJkUHJvamVjdFVJLW1hc3Rlci9zcmMvYXBwL2NyZXN0cm9uLXNkay9jb21wb25lbnRzL3NuaXBwZXQvc25pcHBldC5jb21wb25lbnQudHMuU25pcHBldENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxkaXYgY2xhc3M9XCJjb2wtbWQtNFwiPlxuICA8ZGl2IGNsYXNzPVwiaW5wdXQtZ3JvdXBcIj5cbiAgICA8cHJlPnt7Y29kZX19PC9wcmU+XG4gICAgPHNwYW4gY2xhc3M9XCJpbnB1dC1ncm91cC1idG5cIj5cbiAgICAgICAgICAgIDxidXR0b24gY2xhc3M9XCJidG4gYnRuLWRlZmF1bHRcIiBbY2xhc3MuYnRuLXN1Y2Nlc3NdPVwiZmFsc2VcIiB0eXBlPVwiYnV0dG9uXCIgbmd4Q2xpcGJvYXJkIFtjYkNvbnRlbnRdPVtjb2RlXT5jb3B5PC9idXR0b24+XG4gICAgPC9zcGFuPlxuICA8L2Rpdj5cbjwvZGl2PlxuIiwiPHNuaXBwZXQtY29tcG9uZW50Pjwvc25pcHBldC1jb21wb25lbnQ+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQTtNQUFzQix5Q0FDcEI7VUFBQTtVQUFBLDhCQUF5QjtNQUN2QjtVQUFBLDBEQUFLO1VBQUEsVUFBYywyQ0FDbkI7VUFBQTtVQUFBLDRDQUE4QjtVQUFBLHFCQUN0QjtVQUFBO2NBQUE7WUFBQTtZQUFBO2NBQUE7Y0FBQTtZQUFBO1lBQUE7VUFBQSx1Q0FBQTtVQUFBO2NBQUEsb0NBQXVGLElBQW1CO1VBQUEsV0FBYSwyQ0FDeEg7VUFBQSxXQUNILHVDQUNGO1VBQUE7O0lBSGdGO0lBQWE7SUFBdkYsWUFBMEUsVUFBYSxTQUF2Rjs7O0lBRkg7SUFBQTtJQUVtQztJQUFoQyxXQUFnQyxTQUFoQzs7OztvQkNKWjtNQUFBO2lDQUFBLFVBQUE7TUFBQTtJQUFBOzs7OyJ9
