/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
/* tslint:disable */
/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */ export var styles = ['input[type="range"].multirange[_ngcontent-%COMP%] {\r\n  padding: 0;\r\n  margin: 0;\r\n  vertical-align: top;\r\n}\r\n\r\ninput[type="range"].multirange.original[_ngcontent-%COMP%] {\r\n  position: absolute;\r\n}\r\n\r\ninput[type="range"].multirange.original[_ngcontent-%COMP%]::-webkit-slider-thumb {\r\n  position: relative;\r\n  z-index: 2;\r\n}\r\n\r\ninput[type="range"].multirange.original[_ngcontent-%COMP%]::-moz-range-thumb {\r\n  transform: scale(1); \r\n  z-index: 1;\r\n}\r\n\r\ninput[type="range"].multirange[_ngcontent-%COMP%]::-moz-range-track {\r\n  border-color: transparent; \r\n  border-radius: 5px;\r\n  height: 8px;\r\n  vertical-align:middle;\r\n  border: none;\r\n  cursor: pointer;\r\n}\r\n\r\ninput[type="range"].multirange.ghost[_ngcontent-%COMP%] {\r\n  position: relative;\r\n  background: var(--track-background);\r\n  --track-background: linear-gradient(to right,\r\n  transparent var(--low), var(--range-color) 0,\r\n  var(--range-color) var(--high), transparent 0\r\n  );\r\n  --range-color: #7aa5db;\r\n}\r\n\r\ninput[type="range"].multirange.ghost[_ngcontent-%COMP%]::-webkit-slider-runnable-track {\r\n  background: var(--track-background);\r\n}\r\n\r\ninput[type="range"].multirange.ghost[_ngcontent-%COMP%]::-moz-range-track {\r\n  background: var(--track-background);\r\n}'];
//# sourceMappingURL=slider-range.component.css.shim.ngstyle.js.map