/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './button.component.css.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '@angular/common';
import * as i3 from '../../../../../app/crestron-sdk/components/button/button.component';
const styles_ButtonComponent:any[] = [i0.styles];
export const RenderType_ButtonComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:2,
    styles:styles_ButtonComponent,data:{}});
function View_ButtonComponent_1(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),0,'i',([] as any[]),
      [[8,'className',0]],(null as any),(null as any),(null as any),(null as any)))],
      (null as any),(_ck,_v) => {
        var _co:any = _v.component;
        const currVal_0:any = i1.ɵinlineInterpolate(2,'btn_addon custom_addon ',_co.icon,
            ' ',_co.rotate_icon,'');
        _ck(_v,0,0,currVal_0);
      });
}
function View_ButtonComponent_2(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),0,'i',([] as any[]),
      [[8,'className',0]],(null as any),(null as any),(null as any),(null as any)))],
      (null as any),(_ck,_v) => {
        var _co:any = _v.component;
        const currVal_0:any = i1.ɵinlineInterpolate(2,'btn_addon custom_addon ',_co.icon,
            ' ',_co.rotate_icon,'');
        _ck(_v,0,0,currVal_0);
      });
}
export function View_ButtonComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),10,'div',([] as any[]),
      [[8,'id',0],[8,'className',0]],(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i1.ɵted((null as any),['\n    '])),(_l()(),i1.ɵand(16777216,(null as any),
          (null as any),1,(null as any),View_ButtonComponent_1)),i1.ɵdid(16384,(null as any),
          0,i2.NgIf,[i1.ViewContainerRef,i1.TemplateRef],{ngIf:[0,'ngIf']},(null as any)),
      (_l()(),i1.ɵted((null as any),['\n    '])),(_l()(),i1.ɵeld(0,(null as any),(null as any),
          1,'label',[['class','btn_label custom_label']],(null as any),(null as any),
          (null as any),(null as any),(null as any))),(_l()(),i1.ɵted((null as any),
          ['',''])),(_l()(),i1.ɵted((null as any),['\n    '])),(_l()(),i1.ɵand(16777216,
          (null as any),(null as any),1,(null as any),View_ButtonComponent_2)),i1.ɵdid(16384,
          (null as any),0,i2.NgIf,[i1.ViewContainerRef,i1.TemplateRef],{ngIf:[0,'ngIf']},
          (null as any)),(_l()(),i1.ɵted((null as any),['\n']))],(_ck,_v) => {
    var _co:i3.ButtonComponent = _v.component;
    const currVal_2:any = _co.isDisplayIconLeft;
    _ck(_v,3,0,currVal_2);
    const currVal_4:any = _co.isDisplayIconRight;
    _ck(_v,9,0,currVal_4);
  },(_ck,_v) => {
    var _co:i3.ButtonComponent = _v.component;
    const currVal_0:any = i1.ɵinlineInterpolate(1,'',_co.name,'');
    const currVal_1:any = i1.ɵinlineInterpolate(6,'btn_container ',_co.customClass,
        ' ',_co.size,' ',_co.stretch,' ',_co.shape,' ',_co.type,' ',_co.orientation,
        '');
    _ck(_v,0,0,currVal_0,currVal_1);
    const currVal_3:any = _co.label;
    _ck(_v,6,0,currVal_3);
  });
}
export function View_ButtonComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'btn',([] as any[]),
      (null as any),(null as any),(null as any),View_ButtonComponent_0,RenderType_ButtonComponent)),
      i1.ɵdid(114688,(null as any),0,i3.ButtonComponent,([] as any[]),(null as any),
          (null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const ButtonComponentNgFactory:i1.ComponentFactory<i3.ButtonComponent> = i1.ɵccf('btn',
    i3.ButtonComponent,View_ButtonComponent_Host_0,{name:'name',customClass:'customClass',
        label:'label',icon:'icon',icon_align:'icon_align',shape:'shape',type:'type',
        size:'size',stretch:'stretch',orientation:'orientation'},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovQmxhY2tiaXJkQ2xvbmUvQmxhY2tiaXJkUHJvamVjdFVJL3NyYy9hcHAvY3Jlc3Ryb24tc2RrL2NvbXBvbmVudHMvYnV0dG9uL2J1dHRvbi5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRDovQmxhY2tiaXJkQ2xvbmUvQmxhY2tiaXJkUHJvamVjdFVJL3NyYy9hcHAvY3Jlc3Ryb24tc2RrL2NvbXBvbmVudHMvYnV0dG9uL2J1dHRvbi5jb21wb25lbnQudHMiLCJuZzovLy9EOi9CbGFja2JpcmRDbG9uZS9CbGFja2JpcmRQcm9qZWN0VUkvc3JjL2FwcC9jcmVzdHJvbi1zZGsvY29tcG9uZW50cy9idXR0b24vYnV0dG9uLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRDovQmxhY2tiaXJkQ2xvbmUvQmxhY2tiaXJkUHJvamVjdFVJL3NyYy9hcHAvY3Jlc3Ryb24tc2RrL2NvbXBvbmVudHMvYnV0dG9uL2J1dHRvbi5jb21wb25lbnQudHMuQnV0dG9uQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGRpdiBpZD1cInt7bmFtZX19XCIgY2xhc3M9XCJidG5fY29udGFpbmVyIHt7Y3VzdG9tQ2xhc3N9fSB7e3NpemV9fSB7e3N0cmV0Y2h9fSB7e3NoYXBlfX0ge3t0eXBlfX0ge3tvcmllbnRhdGlvbn19XCI+XHJcbiAgICA8aSAqbmdJZj1cImlzRGlzcGxheUljb25MZWZ0XCIgY2xhc3M9XCJidG5fYWRkb24gY3VzdG9tX2FkZG9uIHt7aWNvbn19IHt7cm90YXRlX2ljb259fVwiPjwvaT5cclxuICAgIDxsYWJlbCBjbGFzcz1cImJ0bl9sYWJlbCBjdXN0b21fbGFiZWxcIj57e2xhYmVsfX08L2xhYmVsPlxyXG4gICAgPGkgKm5nSWY9XCJpc0Rpc3BsYXlJY29uUmlnaHRcIiBjbGFzcz1cImJ0bl9hZGRvbiBjdXN0b21fYWRkb24ge3tpY29ufX0ge3tyb3RhdGVfaWNvbn19XCI+PC9pPlxyXG48L2Rpdj4iLCI8YnRuPjwvYnRuPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7b0JDQ0k7TUFBQTs7O1FBQTZCO1lBQUE7UUFBN0IsV0FBNkIsU0FBN0I7Ozs7b0JBRUE7TUFBQTs7O1FBQThCO1lBQUE7UUFBOUIsV0FBOEIsU0FBOUI7Ozs7b0JBSEo7TUFBQTtNQUFpSCwyQ0FDN0c7VUFBQSw4REFBQTtVQUFBO01BQXlGLDJDQUN6RjtVQUFBO1VBQUEsNENBQXNDO1VBQUEsVUFBaUIsMkNBQ3ZEO1VBQUEsNEVBQUE7VUFBQTtVQUFBLGVBQTBGOztJQUZ2RjtJQUFILFdBQUcsU0FBSDtJQUVHO0lBQUgsV0FBRyxTQUFIOzs7SUFIQztJQUFjO1FBQUE7UUFBQTtJQUFuQixXQUFLLFVBQWMsU0FBbkI7SUFFMEM7SUFBQTs7OztvQkNGMUM7TUFBQTthQUFBO1VBQUE7SUFBQTs7Ozs7OyJ9
