/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './button.component.css.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '@angular/common';
import * as i3 from '../../../../../app/crestron-sdk/components/button/button.component';
const styles_ButtonComponent:any[] = [i0.styles];
export const RenderType_ButtonComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:2,
    styles:styles_ButtonComponent,data:{}});
function View_ButtonComponent_1(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),0,'i',([] as any[]),
      [[8,'className',0]],(null as any),(null as any),(null as any),(null as any)))],
      (null as any),(_ck,_v) => {
        var _co:any = _v.component;
        const currVal_0:any = i1.ɵinlineInterpolate(2,'btn_addon custom_addon ',_co.icon,
            ' ',_co.rotate_icon,'');
        _ck(_v,0,0,currVal_0);
      });
}
function View_ButtonComponent_2(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),0,'i',([] as any[]),
      [[8,'className',0]],(null as any),(null as any),(null as any),(null as any)))],
      (null as any),(_ck,_v) => {
        var _co:any = _v.component;
        const currVal_0:any = i1.ɵinlineInterpolate(2,'btn_addon custom_addon ',_co.icon,
            ' ',_co.rotate_icon,'');
        _ck(_v,0,0,currVal_0);
      });
}
export function View_ButtonComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),10,'div',([] as any[]),
      [[8,'id',0],[8,'className',0]],(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i1.ɵted((null as any),['\n    '])),(_l()(),i1.ɵand(16777216,(null as any),
          (null as any),1,(null as any),View_ButtonComponent_1)),i1.ɵdid(16384,(null as any),
          0,i2.NgIf,[i1.ViewContainerRef,i1.TemplateRef],{ngIf:[0,'ngIf']},(null as any)),
      (_l()(),i1.ɵted((null as any),['\n    '])),(_l()(),i1.ɵeld(0,(null as any),(null as any),
          1,'label',[['class','btn_label custom_label']],(null as any),(null as any),
          (null as any),(null as any),(null as any))),(_l()(),i1.ɵted((null as any),
          ['',''])),(_l()(),i1.ɵted((null as any),['\n    '])),(_l()(),i1.ɵand(16777216,
          (null as any),(null as any),1,(null as any),View_ButtonComponent_2)),i1.ɵdid(16384,
          (null as any),0,i2.NgIf,[i1.ViewContainerRef,i1.TemplateRef],{ngIf:[0,'ngIf']},
          (null as any)),(_l()(),i1.ɵted((null as any),['\n']))],(_ck,_v) => {
    var _co:i3.ButtonComponent = _v.component;
    const currVal_2:any = _co.isDisplayIconLeft;
    _ck(_v,3,0,currVal_2);
    const currVal_4:any = _co.isDisplayIconRight;
    _ck(_v,9,0,currVal_4);
  },(_ck,_v) => {
    var _co:i3.ButtonComponent = _v.component;
    const currVal_0:any = i1.ɵinlineInterpolate(1,'',_co.name,'');
    const currVal_1:any = i1.ɵinlineInterpolate(6,'btn_container ',_co.customClass,
        ' ',_co.size,' ',_co.stretch,' ',_co.shape,' ',_co.type,' ',_co.orientation,
        '');
    _ck(_v,0,0,currVal_0,currVal_1);
    const currVal_3:any = _co.label;
    _ck(_v,6,0,currVal_3);
  });
}
export function View_ButtonComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'btn',([] as any[]),
      (null as any),(null as any),(null as any),View_ButtonComponent_0,RenderType_ButtonComponent)),
      i1.ɵdid(114688,(null as any),0,i3.ButtonComponent,([] as any[]),(null as any),
          (null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const ButtonComponentNgFactory:i1.ComponentFactory<i3.ButtonComponent> = i1.ɵccf('btn',
    i3.ButtonComponent,View_ButtonComponent_Host_0,{name:'name',customClass:'customClass',
        label:'label',icon:'icon',icon_align:'icon_align',shape:'shape',type:'type',
        size:'size',stretch:'stretch',orientation:'orientation'},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvdHltdWQvQmxhY2tiaXJkL0JsYWNrYmlyZFByb2plY3RVSS1tYXN0ZXIvQmxhY2tiaXJkUHJvamVjdFVJLW1hc3Rlci9zcmMvYXBwL2NyZXN0cm9uLXNkay9jb21wb25lbnRzL2J1dHRvbi9idXR0b24uY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL3R5bXVkL0JsYWNrYmlyZC9CbGFja2JpcmRQcm9qZWN0VUktbWFzdGVyL0JsYWNrYmlyZFByb2plY3RVSS1tYXN0ZXIvc3JjL2FwcC9jcmVzdHJvbi1zZGsvY29tcG9uZW50cy9idXR0b24vYnV0dG9uLmNvbXBvbmVudC50cyIsIm5nOi8vL0M6L1VzZXJzL3R5bXVkL0JsYWNrYmlyZC9CbGFja2JpcmRQcm9qZWN0VUktbWFzdGVyL0JsYWNrYmlyZFByb2plY3RVSS1tYXN0ZXIvc3JjL2FwcC9jcmVzdHJvbi1zZGsvY29tcG9uZW50cy9idXR0b24vYnV0dG9uLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvdHltdWQvQmxhY2tiaXJkL0JsYWNrYmlyZFByb2plY3RVSS1tYXN0ZXIvQmxhY2tiaXJkUHJvamVjdFVJLW1hc3Rlci9zcmMvYXBwL2NyZXN0cm9uLXNkay9jb21wb25lbnRzL2J1dHRvbi9idXR0b24uY29tcG9uZW50LnRzLkJ1dHRvbkNvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxkaXYgaWQ9XCJ7e25hbWV9fVwiIGNsYXNzPVwiYnRuX2NvbnRhaW5lciB7e2N1c3RvbUNsYXNzfX0ge3tzaXplfX0ge3tzdHJldGNofX0ge3tzaGFwZX19IHt7dHlwZX19IHt7b3JpZW50YXRpb259fVwiPlxuICAgIDxpICpuZ0lmPVwiaXNEaXNwbGF5SWNvbkxlZnRcIiBjbGFzcz1cImJ0bl9hZGRvbiBjdXN0b21fYWRkb24ge3tpY29ufX0ge3tyb3RhdGVfaWNvbn19XCI+PC9pPlxuICAgIDxsYWJlbCBjbGFzcz1cImJ0bl9sYWJlbCBjdXN0b21fbGFiZWxcIj57e2xhYmVsfX08L2xhYmVsPlxuICAgIDxpICpuZ0lmPVwiaXNEaXNwbGF5SWNvblJpZ2h0XCIgY2xhc3M9XCJidG5fYWRkb24gY3VzdG9tX2FkZG9uIHt7aWNvbn19IHt7cm90YXRlX2ljb259fVwiPjwvaT5cbjwvZGl2PiIsIjxidG4+PC9idG4+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7OztvQkNDSTtNQUFBOzs7UUFBNkI7WUFBQTtRQUE3QixXQUE2QixTQUE3Qjs7OztvQkFFQTtNQUFBOzs7UUFBOEI7WUFBQTtRQUE5QixXQUE4QixTQUE5Qjs7OztvQkFISjtNQUFBO01BQWlILDJDQUM3RztVQUFBLDhEQUFBO1VBQUE7TUFBeUYsMkNBQ3pGO1VBQUE7VUFBQSw0Q0FBc0M7VUFBQSxVQUFpQiwyQ0FDdkQ7VUFBQSw0RUFBQTtVQUFBO1VBQUEsZUFBMEY7O0lBRnZGO0lBQUgsV0FBRyxTQUFIO0lBRUc7SUFBSCxXQUFHLFNBQUg7OztJQUhDO0lBQWM7UUFBQTtRQUFBO0lBQW5CLFdBQUssVUFBYyxTQUFuQjtJQUUwQztJQUFBOzs7O29CQ0YxQztNQUFBO2FBQUE7VUFBQTtJQUFBOzs7Ozs7In0=
