/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../../app/crestron-sdk/controllers/button-controller';
import * as i2 from '../../../../app/crestron-sdk/services/joins.service';
import * as i3 from '../../../../app/crestron-sdk/services/communication.service';
const styles_ButtonController:any[] = ([] as any[]);
export const RenderType_ButtonController:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_ButtonController,data:{}});
export function View_ButtonController_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,([] as any[]),(null as any),(null as any));
}
export function View_ButtonController_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'btn-controller',
      ([] as any[]),(null as any),(null as any),(null as any),View_ButtonController_0,
      RenderType_ButtonController)),i0.ɵdid(245760,(null as any),0,i1.ButtonController,
      [i2.JoinsService,i3.CommunicationService],(null as any),(null as any))],(_ck,
      _v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const ButtonControllerNgFactory:i0.ComponentFactory<i1.ButtonController> = i0.ɵccf('btn-controller',
    i1.ButtonController,View_ButtonController_Host_0,{name:'name',onPress:'onPress',
        onTap:'onTap',onRelease:'onRelease',onFocus:'onFocus',onBlur:'onBlur',runClass:'runClass',
        runFocused:'runFocused',runPressed:'runPressed',runShow:'runShow'},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvdHltdWQvQmxhY2tiaXJkL0JsYWNrYmlyZFByb2plY3RVSS1tYXN0ZXIvQmxhY2tiaXJkUHJvamVjdFVJLW1hc3Rlci9zcmMvYXBwL2NyZXN0cm9uLXNkay9jb250cm9sbGVycy9idXR0b24tY29udHJvbGxlci5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy90eW11ZC9CbGFja2JpcmQvQmxhY2tiaXJkUHJvamVjdFVJLW1hc3Rlci9CbGFja2JpcmRQcm9qZWN0VUktbWFzdGVyL3NyYy9hcHAvY3Jlc3Ryb24tc2RrL2NvbnRyb2xsZXJzL2J1dHRvbi1jb250cm9sbGVyLnRzIiwibmc6Ly8vQzovVXNlcnMvdHltdWQvQmxhY2tiaXJkL0JsYWNrYmlyZFByb2plY3RVSS1tYXN0ZXIvQmxhY2tiaXJkUHJvamVjdFVJLW1hc3Rlci9zcmMvYXBwL2NyZXN0cm9uLXNkay9jb250cm9sbGVycy9idXR0b24tY29udHJvbGxlci50cy5CdXR0b25Db250cm9sbGVyX0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGJ0bi1jb250cm9sbGVyPjwvYnRuLWNvbnRyb2xsZXI+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7OztvQkNBQTtNQUFBO2lDQUFBLFVBQUE7TUFBQTs7SUFBQTs7Ozs7OyJ9
