/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../../app/crestron-sdk/controllers/list-controller';
import * as i2 from '../../../../app/crestron-sdk/services/joins.service';
import * as i3 from '../../../../app/crestron-sdk/services/communication.service';
const styles_ListController:any[] = ([] as any[]);
export const RenderType_ListController:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_ListController,data:{}});
export function View_ListController_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'span',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i0.ɵted((null as any),['list']))],(null as any),(null as any));
}
export function View_ListController_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'list-controller-component',
      ([] as any[]),(null as any),(null as any),(null as any),View_ListController_0,
      RenderType_ListController)),i0.ɵdid(245760,(null as any),0,i1.ListController,
      [i2.JoinsService,i3.CommunicationService],(null as any),(null as any))],(_ck,
      _v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const ListControllerNgFactory:i0.ComponentFactory<i1.ListController> = i0.ɵccf('list-controller-component',
    i1.ListController,View_ListController_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovQmxhY2tiaXJkQ2xvbmUvQmxhY2tiaXJkUHJvamVjdFVJL3NyYy9hcHAvY3Jlc3Ryb24tc2RrL2NvbnRyb2xsZXJzL2xpc3QtY29udHJvbGxlci5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9EOi9CbGFja2JpcmRDbG9uZS9CbGFja2JpcmRQcm9qZWN0VUkvc3JjL2FwcC9jcmVzdHJvbi1zZGsvY29udHJvbGxlcnMvbGlzdC1jb250cm9sbGVyLnRzIiwibmc6Ly8vRDovQmxhY2tiaXJkQ2xvbmUvQmxhY2tiaXJkUHJvamVjdFVJL3NyYy9hcHAvY3Jlc3Ryb24tc2RrL2NvbnRyb2xsZXJzL2xpc3QtY29udHJvbGxlci50cy5MaXN0Q29udHJvbGxlci5odG1sIiwibmc6Ly8vRDovQmxhY2tiaXJkQ2xvbmUvQmxhY2tiaXJkUHJvamVjdFVJL3NyYy9hcHAvY3Jlc3Ryb24tc2RrL2NvbnRyb2xsZXJzL2xpc3QtY29udHJvbGxlci50cy5MaXN0Q29udHJvbGxlcl9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxzcGFuPmxpc3Q8L3NwYW4+IiwiPGxpc3QtY29udHJvbGxlci1jb21wb25lbnQ+PC9saXN0LWNvbnRyb2xsZXItY29tcG9uZW50PiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQSx3RUFBTTthQUFBOzs7b0JDQU47TUFBQTsrQkFBQSxVQUFBO01BQUE7O0lBQUE7Ozs7In0=
