/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../../app/crestron-sdk/controllers/slider-controller';
import * as i2 from '../../../../app/crestron-sdk/services/joins.service';
import * as i3 from '../../../../app/crestron-sdk/services/communication.service';
const styles_SliderController:any[] = ([] as any[]);
export const RenderType_SliderController:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_SliderController,data:{}});
export function View_SliderController_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,([] as any[]),(null as any),(null as any));
}
export function View_SliderController_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'slider-controller',
      ([] as any[]),(null as any),(null as any),(null as any),View_SliderController_0,
      RenderType_SliderController)),i0.ɵdid(245760,(null as any),0,i1.SliderController,
      [i2.JoinsService,i3.CommunicationService],(null as any),(null as any))],(_ck,
      _v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const SliderControllerNgFactory:i0.ComponentFactory<i1.SliderController> = i0.ɵccf('slider-controller',
    i1.SliderController,View_SliderController_Host_0,{name:'name',onSlide:'onSlide',
        onSlideEnd:'onSlideEnd',runClass:'runClass',runEnabled:'runEnabled',runShow:'runShow',
        runValue:'runValue',runValuePair:'runValuePair'},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovQmxhY2tiaXJkQ2xvbmUvQmxhY2tiaXJkUHJvamVjdFVJL3NyYy9hcHAvY3Jlc3Ryb24tc2RrL2NvbnRyb2xsZXJzL3NsaWRlci1jb250cm9sbGVyLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Q6L0JsYWNrYmlyZENsb25lL0JsYWNrYmlyZFByb2plY3RVSS9zcmMvYXBwL2NyZXN0cm9uLXNkay9jb250cm9sbGVycy9zbGlkZXItY29udHJvbGxlci50cyIsIm5nOi8vL0Q6L0JsYWNrYmlyZENsb25lL0JsYWNrYmlyZFByb2plY3RVSS9zcmMvYXBwL2NyZXN0cm9uLXNkay9jb250cm9sbGVycy9zbGlkZXItY29udHJvbGxlci50cy5TbGlkZXJDb250cm9sbGVyX0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPHNsaWRlci1jb250cm9sbGVyPjwvc2xpZGVyLWNvbnRyb2xsZXI+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7OztvQkNBQTtNQUFBO2lDQUFBLFVBQUE7TUFBQTs7SUFBQTs7Ozs7OyJ9
