/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
/* tslint:disable */
export var styles = ['video[_ngcontent-%COMP%] {\n  margin-top: 5%;\n}'];
//# sourceMappingURL=video.component.css.shim.ngstyle.js.map