/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './video.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '../../../../../app/crestron-sdk/components/video/video.component';
import * as i3 from '@angular/platform-browser';
const styles_VideoComponent:any[] = [i0.styles];
export const RenderType_VideoComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_VideoComponent,data:{}});
export function View_VideoComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[i1.ɵqud(402653184,1,{video:0}),(_l()(),i1.ɵeld(0,[[1,0],['video',
      1]],(null as any),0,'video',([] as any[]),[[8,'src',4]],(null as any),(null as any),
      (null as any),(null as any))),(_l()(),i1.ɵted((null as any),['\n']))],(null as any),
      (_ck,_v) => {
        var _co:i2.VideoComponent = _v.component;
        const currVal_0:any = _co.src;
        _ck(_v,1,0,currVal_0);
      });
}
export function View_VideoComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-video',([] as any[]),
      (null as any),(null as any),(null as any),View_VideoComponent_0,RenderType_VideoComponent)),
      i1.ɵdid(245760,(null as any),0,i2.VideoComponent,[i3.DomSanitizer],(null as any),
          (null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const VideoComponentNgFactory:i1.ComponentFactory<i2.VideoComponent> = i1.ɵccf('app-video',
    i2.VideoComponent,View_VideoComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovQmxhY2tiaXJkQ2xvbmUvQmxhY2tiaXJkUHJvamVjdFVJL3NyYy9hcHAvY3Jlc3Ryb24tc2RrL2NvbXBvbmVudHMvdmlkZW8vdmlkZW8uY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Q6L0JsYWNrYmlyZENsb25lL0JsYWNrYmlyZFByb2plY3RVSS9zcmMvYXBwL2NyZXN0cm9uLXNkay9jb21wb25lbnRzL3ZpZGVvL3ZpZGVvLmNvbXBvbmVudC50cyIsIm5nOi8vL0Q6L0JsYWNrYmlyZENsb25lL0JsYWNrYmlyZFByb2plY3RVSS9zcmMvYXBwL2NyZXN0cm9uLXNkay9jb21wb25lbnRzL3ZpZGVvL3ZpZGVvLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRDovQmxhY2tiaXJkQ2xvbmUvQmxhY2tiaXJkUHJvamVjdFVJL3NyYy9hcHAvY3Jlc3Ryb24tc2RrL2NvbXBvbmVudHMvdmlkZW8vdmlkZW8uY29tcG9uZW50LnRzLlZpZGVvQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPHZpZGVvICN2aWRlbyBbc3JjXT1cInNyY1wiPjwvdmlkZW8+XHJcbiIsIjxhcHAtdmlkZW8+PC9hcHAtdmlkZW8+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7OzttRENBQTtNQUFBO01BQUEsOEJBQWtDOzs7UUFBcEI7UUFBZCxXQUFjLFNBQWQ7Ozs7b0JDQUE7TUFBQTthQUFBO1VBQUE7SUFBQTs7OzsifQ==
