/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
/* tslint:disable */
/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */ export var styles = ['.button_wrapper{\r\n    position: relative;\r\n    display: block;\r\n    width: 90%;\r\n    height: 100%;\r\n    margin-left: auto;\r\n    margin-right: auto;\r\n}\r\n\r\n.button_container{\r\n  position: relative;\r\n  width: 15%;\r\n  height: 15%;\r\n  min-width: 300px;\r\n  min-height: 250px;\r\n  border: 1px solid rgb(50,54,56);\r\n  border: 1px solid rgba(50,54,56, .1);\r\n  -webkit-background-clip: padding-box; \r\n  background-clip: padding-box;\r\n  box-sizing: border-box;\r\n  margin: 4% 2%;\r\n  display: inline-flex;\r\n}\r\n\r\n.button_container:hover {\r\n  box-shadow: 0 0 16px rgba(0, 0, 0, 0.2);\r\n}\r\n\r\nh5 {\r\n    padding: 15px;\r\n    text-align: center;\r\n    height: 20%;\r\n    width: 100%;\r\n} \r\n\r\n.crestron_button_container {\r\n    display: block;\r\n    position: absolute;\r\n    display: block;\r\n    margin-left: auto;\r\n    margin-right: auto;\r\n    width: 200px;\r\n    height: 100px;\r\n    text-align: center;\r\n    top: 50%;\r\n    left: 50%;\r\n    transform: translate(-50%, -50%);\r\n}\r\n\r\n.crestron_button_container div{\r\n    display: inline-block;\r\n    position: relative;\r\n    top: 50%;   \r\n}\r\n\r\n.crestron_button_container .vertical{\r\n  margin-top: 10%;\r\n}\r\n\r\n.common_btn_style {\r\n    border: .5px solid #588ed3;\r\n    background-color: #588ed3;\r\n    color: #f0fff0;\r\n}\r\n\r\n\r\n\r\n\r\n'];
//# sourceMappingURL=gallery-button.component.css.ngstyle.js.map