/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './spec-list.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '../../../../app/gallery/gallery-spec/spec-list.component';
const styles_GallerySpecComponent:any[] = [i0.styles];
export const RenderType_GallerySpecComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_GallerySpecComponent,data:{}});
export function View_GallerySpecComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'span',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted((null as any),['TO DO'])),(_l()(),i1.ɵted((null as any),['\n']))],(null as any),
      (null as any));
}
export function View_GallerySpecComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'gallery-spec',
      ([] as any[]),(null as any),(null as any),(null as any),View_GallerySpecComponent_0,
      RenderType_GallerySpecComponent)),i1.ɵdid(49152,(null as any),0,i2.GallerySpecComponent,
      ([] as any[]),(null as any),(null as any))],(null as any),(null as any));
}
export const GallerySpecComponentNgFactory:i1.ComponentFactory<i2.GallerySpecComponent> = i1.ɵccf('gallery-spec',
    i2.GallerySpecComponent,View_GallerySpecComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovQmxhY2tiaXJkQ2xvbmUvQmxhY2tiaXJkUHJvamVjdFVJL3NyYy9hcHAvZ2FsbGVyeS9nYWxsZXJ5LXNwZWMvc3BlYy1saXN0LmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9EOi9CbGFja2JpcmRDbG9uZS9CbGFja2JpcmRQcm9qZWN0VUkvc3JjL2FwcC9nYWxsZXJ5L2dhbGxlcnktc3BlYy9zcGVjLWxpc3QuY29tcG9uZW50LnRzIiwibmc6Ly8vRDovQmxhY2tiaXJkQ2xvbmUvQmxhY2tiaXJkUHJvamVjdFVJL3NyYy9hcHAvZ2FsbGVyeS9nYWxsZXJ5LXNwZWMvc3BlYy1saXN0LmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRDovQmxhY2tiaXJkQ2xvbmUvQmxhY2tiaXJkUHJvamVjdFVJL3NyYy9hcHAvZ2FsbGVyeS9nYWxsZXJ5LXNwZWMvc3BlYy1saXN0LmNvbXBvbmVudC50cy5HYWxsZXJ5U3BlY0NvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxzcGFuPlRPIERPPC9zcGFuPlxyXG4iLCI8Z2FsbGVyeS1zcGVjPjwvZ2FsbGVyeS1zcGVjPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7OztvQkNBQTtNQUFBLHdFQUFNO2FBQUEsMkJBQVk7Ozs7b0JDQWxCO01BQUE7cUNBQUEsVUFBQTtNQUFBOzs7In0=
