/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
/* tslint:disable */
/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */ export var styles = ['span[_ngcontent-%COMP%] {\r\n  font-size: 30px;\r\n  padding-left: 5%;\r\n  padding-top: 5%;\r\n  display: block;\r\n}'];
//# sourceMappingURL=spec-list.component.css.shim.ngstyle.js.map