/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './spec-list.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '../../../../app/gallery/gallery-spec/spec-list.component';
const styles_GallerySpecComponent:any[] = [i0.styles];
export const RenderType_GallerySpecComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_GallerySpecComponent,data:{}});
export function View_GallerySpecComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'span',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted((null as any),['TO DO'])),(_l()(),i1.ɵted((null as any),['\n']))],(null as any),
      (null as any));
}
export function View_GallerySpecComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'gallery-spec',
      ([] as any[]),(null as any),(null as any),(null as any),View_GallerySpecComponent_0,
      RenderType_GallerySpecComponent)),i1.ɵdid(49152,(null as any),0,i2.GallerySpecComponent,
      ([] as any[]),(null as any),(null as any))],(null as any),(null as any));
}
export const GallerySpecComponentNgFactory:i1.ComponentFactory<i2.GallerySpecComponent> = i1.ɵccf('gallery-spec',
    i2.GallerySpecComponent,View_GallerySpecComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvdHltdWQvQmxhY2tiaXJkL0JsYWNrYmlyZFByb2plY3RVSS1tYXN0ZXIvQmxhY2tiaXJkUHJvamVjdFVJLW1hc3Rlci9zcmMvYXBwL2dhbGxlcnkvZ2FsbGVyeS1zcGVjL3NwZWMtbGlzdC5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovVXNlcnMvdHltdWQvQmxhY2tiaXJkL0JsYWNrYmlyZFByb2plY3RVSS1tYXN0ZXIvQmxhY2tiaXJkUHJvamVjdFVJLW1hc3Rlci9zcmMvYXBwL2dhbGxlcnkvZ2FsbGVyeS1zcGVjL3NwZWMtbGlzdC5jb21wb25lbnQudHMiLCJuZzovLy9DOi9Vc2Vycy90eW11ZC9CbGFja2JpcmQvQmxhY2tiaXJkUHJvamVjdFVJLW1hc3Rlci9CbGFja2JpcmRQcm9qZWN0VUktbWFzdGVyL3NyYy9hcHAvZ2FsbGVyeS9nYWxsZXJ5LXNwZWMvc3BlYy1saXN0LmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvdHltdWQvQmxhY2tiaXJkL0JsYWNrYmlyZFByb2plY3RVSS1tYXN0ZXIvQmxhY2tiaXJkUHJvamVjdFVJLW1hc3Rlci9zcmMvYXBwL2dhbGxlcnkvZ2FsbGVyeS1zcGVjL3NwZWMtbGlzdC5jb21wb25lbnQudHMuR2FsbGVyeVNwZWNDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8c3Bhbj5UTyBETzwvc3Bhbj5cbiIsIjxnYWxsZXJ5LXNwZWM+PC9nYWxsZXJ5LXNwZWM+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7O29CQ0FBO01BQUEsd0VBQU07YUFBQSwyQkFBWTs7OztvQkNBbEI7TUFBQTtxQ0FBQSxVQUFBO01BQUE7OzsifQ==
