/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
/* tslint:disable */
export var styles = ['span[_ngcontent-%COMP%] {\n  font-size: 30px;\n  padding-left: 5%;\n  padding-top: 5%;\n  display: block;\n}'];
//# sourceMappingURL=spec-list.component.css.shim.ngstyle.js.map