/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
/* tslint:disable */
/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */ export var styles = ['.slider_wrapper{\r\n    position: relative;\r\n    display: block;\r\n    width: 90%;\r\n    height: 100%;\r\n    margin-left: auto;\r\n    margin-right: auto;\r\n}\r\n\r\n.slider_container{\r\n  position: relative;\r\n  width: 15%;\r\n  height: 40%;\r\n  min-width: 600px;\r\n  min-height: 350px;\r\n  \r\n  margin-top: 5%;\r\n  border: 1px solid rgb(50,54,56);\r\n  border: 1px solid rgba(50,54,56, .1);\r\n  -webkit-background-clip: padding-box; \r\n  background-clip: padding-box;\r\n  margin: 5% 4%;\r\n  display: inline-flex;\r\n}\r\n\r\n.slider_container:hover {\r\n  box-shadow: 0 0 16px rgba(0, 0, 0, 0.2);\r\n}\r\n\r\nh5 {\r\n    padding: 15px;\r\n    text-align: center;\r\n    height: 20%;\r\n    width: 100%;\r\n}\r\n\r\n.crestron_slider_container {\r\n    position: absolute;\r\n    display: block;\r\n    margin-left: auto;\r\n    margin-right: auto;\r\n    width: 400px;\r\n    height: 100px;\r\n    text-align: center;\r\n    top: 50%;\r\n    left: 50%;\r\n    transform: translate(-50%, -50%);\r\n}\r\n\r\n.crestron_slider_container .slider_default{\r\n    display: inline-block;\r\n    position: relative;\r\n    top: 50%; \r\n    /* transform: translateY(-50%);\r\n    -webkit-transform: translateY(-50%);*/\r\n  \r\n}\r\n\r\n.crestron_slider_container .vertical{\r\n  margin-top: 10%;\r\n}\r\n\r\n.common_slider_style {\r\n    border: .5px solid #588ed3;\r\n    background-color: #588ed3; \r\n}'];
//# sourceMappingURL=gallery-slider.component.css.ngstyle.js.map