/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['list-component[_ngcontent-%COMP%], [listComponent][_ngcontent-%COMP%]{\r\n  width: 420px;\r\n  height: 65%;\r\n  border: 1px solid rgb(50,54,56);\r\n  border: 1px solid rgba(50,54,56, .1);\r\n  -webkit-background-clip: padding-box;\r\n  background-clip: padding-box;\r\n  margin: 5% auto;\r\n  display: inline-block;\r\n  margin-left: 3%;\r\n}\r\n\r\n#layout-content.slide[_ngcontent-%COMP%]   list-component[_ngcontent-%COMP%], #layout-content.slide[_ngcontent-%COMP%]   [listComponent][_ngcontent-%COMP%]{\r\n  margin: 5% calc(30% - 200px) !important;\r\n}\r\n\r\n\r\nlist-component[_ngcontent-%COMP%]:hover, [listComponent][_ngcontent-%COMP%]:hover {\r\n  box-shadow: 0 0 16px rgba(0, 0, 0, 0.2);\r\n}\r\n\r\n.common_btn_style[_ngcontent-%COMP%] {\r\n    border: .5px solid #588ed3;\r\n    background-color: #588ed3;\r\n    color: #f0fff0;\r\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovQmxhY2tiaXJkQ2xvbmUvQmxhY2tiaXJkUHJvamVjdFVJL3NyYy9hcHAvZ2FsbGVyeS9nYWxsZXJ5LWxpc3QvZ2FsbGVyeS1saXN0LmNvbXBvbmVudC5jc3Muc2hpbS5uZ3N0eWxlLnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRDovQmxhY2tiaXJkQ2xvbmUvQmxhY2tiaXJkUHJvamVjdFVJL3NyYy9hcHAvZ2FsbGVyeS9nYWxsZXJ5LWxpc3QvZ2FsbGVyeS1saXN0LmNvbXBvbmVudC5jc3MiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
