/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
/* tslint:disable */
export var styles = ['list-component[_ngcontent-%COMP%], [listComponent][_ngcontent-%COMP%]{\n  width: 420px;\n  height: 65%;\n  border: 1px solid rgb(50,54,56);\n  border: 1px solid rgba(50,54,56, .1);\n  -webkit-background-clip: padding-box;\n  background-clip: padding-box;\n  margin: 5% auto;\n  display: inline-block;\n  margin-left: 3%;\n}\n\n#layout-content.slide[_ngcontent-%COMP%]   list-component[_ngcontent-%COMP%], #layout-content.slide[_ngcontent-%COMP%]   [listComponent][_ngcontent-%COMP%]{\n  margin: 5% calc(30% - 200px) !important;\n}\n\n\nlist-component[_ngcontent-%COMP%]:hover, [listComponent][_ngcontent-%COMP%]:hover {\n  box-shadow: 0 0 16px rgba(0, 0, 0, 0.2);\n}\n\n.common_btn_style[_ngcontent-%COMP%] {\n    border: .5px solid #588ed3;\n    background-color: #588ed3;\n    color: #f0fff0;\n}\n.common_slider_style[_ngcontent-%COMP%] {\n    border: .5px solid #588ed3;\n    background-color: #588ed3; \n}'];
//# sourceMappingURL=gallery-list.component.css.shim.ngstyle.js.map