/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['list-component[_ngcontent-%COMP%], [listComponent][_ngcontent-%COMP%]{\n  width: 420px;\n  height: 65%;\n  border: 1px solid rgb(50,54,56);\n  border: 1px solid rgba(50,54,56, .1);\n  -webkit-background-clip: padding-box;\n  background-clip: padding-box;\n  margin: 5% auto;\n  display: inline-block;\n  margin-left: 3%;\n}\n\n#layout-content.slide[_ngcontent-%COMP%]   list-component[_ngcontent-%COMP%], #layout-content.slide[_ngcontent-%COMP%]   [listComponent][_ngcontent-%COMP%]{\n  margin: 5% calc(30% - 200px) !important;\n}\n\n\nlist-component[_ngcontent-%COMP%]:hover, [listComponent][_ngcontent-%COMP%]:hover {\n  box-shadow: 0 0 16px rgba(0, 0, 0, 0.2);\n}\n\n.common_btn_style[_ngcontent-%COMP%] {\n    border: .5px solid #588ed3;\n    background-color: #588ed3;\n    color: #f0fff0;\n}\n.common_slider_style[_ngcontent-%COMP%] {\n    border: .5px solid #588ed3;\n    background-color: #588ed3; \n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvdHltdWQvQmxhY2tiaXJkL0JsYWNrYmlyZFByb2plY3RVSS1tYXN0ZXIvQmxhY2tiaXJkUHJvamVjdFVJLW1hc3Rlci9zcmMvYXBwL2dhbGxlcnkvZ2FsbGVyeS1saXN0L2dhbGxlcnktbGlzdC5jb21wb25lbnQuY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL3R5bXVkL0JsYWNrYmlyZC9CbGFja2JpcmRQcm9qZWN0VUktbWFzdGVyL0JsYWNrYmlyZFByb2plY3RVSS1tYXN0ZXIvc3JjL2FwcC9nYWxsZXJ5L2dhbGxlcnktbGlzdC9nYWxsZXJ5LWxpc3QuY29tcG9uZW50LmNzcyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
