/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
/* tslint:disable */
/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */ export var styles = ['list-component[_ngcontent-%COMP%], [listComponent][_ngcontent-%COMP%]{\r\n  width: 420px;\r\n  height: 65%;\r\n  border: 1px solid rgb(50,54,56);\r\n  border: 1px solid rgba(50,54,56, .1);\r\n  -webkit-background-clip: padding-box;\r\n  background-clip: padding-box;\r\n  margin: 5% auto;\r\n  display: inline-block;\r\n  margin-left: 3%;\r\n}\r\n\r\n#layout-content.slide[_ngcontent-%COMP%]   list-component[_ngcontent-%COMP%], #layout-content.slide[_ngcontent-%COMP%]   [listComponent][_ngcontent-%COMP%]{\r\n  margin: 5% calc(30% - 200px) !important;\r\n}\r\n\r\n\r\nlist-component[_ngcontent-%COMP%]:hover, [listComponent][_ngcontent-%COMP%]:hover {\r\n  box-shadow: 0 0 16px rgba(0, 0, 0, 0.2);\r\n}\r\n\r\n.common_btn_style[_ngcontent-%COMP%] {\r\n    border: .5px solid #588ed3;\r\n    background-color: #588ed3;\r\n    color: #f0fff0;\r\n}'];
//# sourceMappingURL=gallery-list.component.css.shim.ngstyle.js.map